version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:815254798932:task-definition/webapp-taskdef:4"
        LoadBalancerInfo:
          ContainerName: "webapp"
          ContainerPort: 8080
