services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build: ./notes-taking-app
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:80"
