version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
